/* Carestep Home PWA v10.0-B · read-only hospital health timeline */
(() => {
  'use strict';
  const API='https://carestep-ai-api.kk04sdw.workers.dev';
  const SESSION_KEY='carestep_home_session_v1';
  const $=id=>document.getElementById(id);
  const TYPE_META={weight:{label:'체중',icon:'kg'},vaccination:{label:'접종',icon:'V'},heartworm:{label:'사상충',icon:'H'},visit:{label:'진료',icon:'+'},journey:{label:'Journey',icon:'J'}};
  const state={token:localStorage.getItem(SESSION_KEY)||'',inviteToken:new URLSearchParams(location.search).get('invite')||'',installPrompt:null,home:null,active:null,timeline:null,filter:'all'};
  const views=['loadingView','inviteView','loginView','dashboardView','patientView','errorView'];
  const esc=v=>String(v??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]));
  const speciesLabel=v=>({dog:'강아지',cat:'고양이',other:'반려동물'})[v]||'반려동물';
  const sexLabel=v=>({male:'수컷',female:'암컷',unknown:'성별 미확인'})[v]||'성별 미확인';
  const sourceLabel=v=>v==='system'?'병원 자동 기록':'병원 기록';
  const dateLabel=v=>{if(!v)return '미입력';const d=new Date(v+'T00:00:00');return Number.isNaN(d.getTime())?v:d.toLocaleDateString('ko-KR',{year:'numeric',month:'short',day:'numeric'});};
  function show(id){for(const key of views){const el=$(key);if(el)el.hidden=key!==id;}window.scrollTo({top:0,behavior:'smooth'});}
  function status(id,text='',kind=''){const el=$(id);if(!el)return;el.textContent=text;el.className='home-status '+kind;}
  async function api(path,opt={}){const headers={'Content-Type':'application/json',...(opt.headers||{})};if(opt.auth!==false&&state.token)headers.Authorization='Bearer '+state.token;let response;try{response=await fetch(API+path,{...opt,headers,cache:'no-store'});}catch{throw new Error(navigator.onLine?'서버에 연결하지 못했습니다. 잠시 후 다시 시도해주세요.':'인터넷 연결을 확인해주세요.');}let data={};try{data=await response.json();}catch{}if(!response.ok)throw Object.assign(new Error(data.error||'요청을 처리하지 못했습니다.'),{status:response.status});return data;}
  function patientHtml(p){return `<div class="invite-pet"><span class="pet-avatar ${p.species==='cat'?'cat':''}">${p.species==='cat'?'CAT':'PET'}</span><span><b>${esc(p.name||'이름 미입력')}</b><span>${esc([speciesLabel(p.species),p.breed].filter(Boolean).join(' · '))}</span></span></div>`;}
  async function loadInvite(){show('loadingView');try{const data=await api('/home/invite/'+encodeURIComponent(state.inviteToken),{method:'GET',auth:false});const invite=data.invite;$('inviteGuardianName').textContent=invite.guardianName||'보호자';$('inviteLead').textContent=`${invite.clinicName}에서 ${(invite.patients||[]).length}마리의 연결을 보냈습니다.`;$('inviteClinic').textContent='🏥 '+invite.clinicName;$('invitePatients').innerHTML=(invite.patients||[]).map(patientHtml).join('');$('invitePhoneHint').textContent=`${invite.phoneHint}로 표시되는 병원 등록 번호의 끝 4자리를 입력해주세요.`;show('inviteView');}catch(e){showError(e.message);}}
  async function acceptInvite(event){event.preventDefault();status('inviteStatus');const button=$('inviteSubmit');button.disabled=true;button.textContent='안전하게 연결하는 중…';try{const data=await api('/home/invite/'+encodeURIComponent(state.inviteToken),{method:'POST',auth:false,body:JSON.stringify({phoneLast4:$('inviteLast4').value,password:$('invitePassword').value,termsAccepted:$('inviteTerms').checked,privacyAccepted:$('invitePrivacy').checked})});state.token=data.session.token;localStorage.setItem(SESSION_KEY,state.token);history.replaceState({},'',location.pathname);renderHome(data.home);show('dashboardView');}catch(e){status('inviteStatus',e.message,'error');}finally{button.disabled=false;button.textContent='계정 만들고 환자 연결';}}
  async function login(event){event.preventDefault();status('loginStatus');const button=$('loginSubmit');button.disabled=true;button.textContent='로그인 중…';try{const data=await api('/home/login',{method:'POST',auth:false,body:JSON.stringify({phone:$('loginPhone').value,password:$('loginPassword').value})});state.token=data.session.token;localStorage.setItem(SESSION_KEY,state.token);renderHome(data.home);show('dashboardView');}catch(e){status('loginStatus',e.message,'error');}finally{button.disabled=false;button.textContent='로그인';}}
  function connectionHtml(c,locked){return `<article class="connection-clinic"><div class="connection-clinic-head"><div><span>연결 병원</span><b>${esc(c.clinicName)}</b></div><small>연결됨</small></div><div class="connection-pets">${(c.patients||[]).map(p=>`<button class="connection-pet" type="button" data-home-patient="${esc(p.id)}" ${locked?'disabled':''}><span class="pet-avatar ${p.species==='cat'?'cat':''}">${p.species==='cat'?'CAT':'PET'}</span><span><b>${esc(p.name)}</b><small>${esc([speciesLabel(p.species),p.breed,sexLabel(p.sex)].filter(Boolean).join(' · '))}</small><em>${locked?'동의 후 확인':'건강 기록 보기 →'}</em></span></button>`).join('')}</div></article>`;}
  function renderHome(home){state.home=home;$('homeUserName').textContent=home?.user?.displayName||'보호자';const locked=!!home?.consentRequired,connections=home?.connections||[];$('homeHealthConsent').hidden=!locked;$('homeConnections').innerHTML=connections.length?connections.map(c=>connectionHtml(c,locked)).join(''):'<div class="stage-note"><b>연결된 환자가 없습니다</b><p>병원에 환자 연결 상태를 확인해주세요.</p></div>';$('homeConnections').querySelectorAll('[data-home-patient]').forEach(button=>button.addEventListener('click',()=>openPatient(button.dataset.homePatient)));}
  function patientContext(patientId){for(const connection of (state.home?.connections||[])){const patient=(connection.patients||[]).find(p=>p.id===patientId);if(patient)return {patient,connection};}return null;}
  async function acceptHealthConsent(){if(!$('homeHealthConsentCheck').checked){status('homeHealthConsentStatus','건강기록 제공 안내에 동의해주세요.','error');return;}const button=$('homeHealthConsentSubmit');button.disabled=true;try{const data=await api('/home/health-consent',{method:'POST',body:JSON.stringify({privacyAccepted:true})});renderHome(data.home);status('homeHealthConsentStatus','동의가 완료되었습니다. 이제 환자 건강 기록을 확인할 수 있습니다.','ok');}catch(e){status('homeHealthConsentStatus',e.message,'error');}finally{button.disabled=false;}}
  function chartHtml(series){if(!series||series.length<2)return '<div class="home-chart-empty">체중 기록이 2회 이상 쌓이면 변화 그래프가 표시됩니다.</div>';const pts=series.slice(-10),values=pts.map(x=>Number(x.value)),min=Math.min(...values),max=Math.max(...values),range=max-min||1,w=520,h=120,p=20,coords=pts.map((x,i)=>({x:p+i*(w-p*2)/Math.max(1,pts.length-1),y:h-p-(Number(x.value)-min)*(h-p*2)/range,v:Number(x.value),d:x.date}));return `<div class="home-chart"><svg viewBox="0 0 ${w} ${h}" role="img" aria-label="최근 체중 변화"><line x1="${p}" y1="${h-p}" x2="${w-p}" y2="${h-p}"/><polyline points="${coords.map(x=>`${x.x},${x.y}`).join(' ')}"/>${coords.map(x=>`<circle cx="${x.x}" cy="${x.y}" r="4"><title>${esc(x.d)} · ${x.v}kg</title></circle>`).join('')}</svg><div><span>${esc(pts[0].date)}</span><b>${min===max?`${min}kg`:`${min}–${max}kg`}</b><span>${esc(pts.at(-1).date)}</span></div></div>`;}
  function eventHtml(e){const meta=TYPE_META[e.type]||{label:e.type,icon:'·'},value=e.type==='weight'&&e.value!==''?`<strong>${esc(e.value)}kg</strong>`:'',due=e.nextDueDate?`<div class="home-event-due"><span>다음 예정</span><b>${dateLabel(e.nextDueDate)}</b></div>`:'',note=e.homeNote?`<p>${esc(e.homeNote)}</p>`:'',journey=e.type==='journey'?`<span class="home-event-status">${e.status==='completed'?'완료':'진행 중'}</span>`:'';return `<article class="home-event"><div class="home-event-marker type-${esc(e.type)}">${esc(meta.icon)}</div><div class="home-event-body"><div class="home-event-head"><span>${dateLabel(e.eventDate)}</span>${journey}</div><div class="home-event-title"><b>${esc(e.title||meta.label)}</b>${value}</div><div class="home-event-meta"><span>${esc(meta.label)}</span><span>${esc(sourceLabel(e.source))}</span></div>${due}${note}</div></article>`;}
  function renderTimeline(){const data=state.timeline;if(!data)return;const rows=state.filter==='all'?data.events:(data.events||[]).filter(e=>e.type===state.filter),next=data.summary?.upcoming;$('patientLatestWeight').textContent=data.summary?.latestWeightKg!==''&&data.summary?.latestWeightKg!=null?`${data.summary.latestWeightKg}kg`:'미입력';$('patientNextDate').textContent=next?dateLabel(next.nextDueDate):'없음';$('patientNextTitle').textContent=next?.title||'예정된 일정 없음';$('patientRecordCount').textContent=`${Number(data.summary?.total)||0}건`;$('patientWeightChart').innerHTML=chartHtml(data.weightSeries||[]);$('patientTimelineFilters').innerHTML=[['all','전체'],...Object.entries(TYPE_META).map(([k,v])=>[k,v.label])].map(([k,v])=>`<button class="${state.filter===k?'active':''}" type="button" data-home-filter="${k}">${esc(v)}</button>`).join('');$('patientTimelineList').innerHTML=rows.length?rows.map(eventHtml).join(''):'<div class="home-timeline-empty"><b>표시할 건강 기록이 없습니다</b><p>병원에서 공개한 기록이 이곳에 날짜순으로 표시됩니다.</p></div>';$('patientTimelineFilters').querySelectorAll('[data-home-filter]').forEach(button=>button.addEventListener('click',()=>{state.filter=button.dataset.homeFilter;renderTimeline();}));}
  async function openPatient(patientId){const context=patientContext(patientId);if(!context)return;state.active=context;state.filter='all';$('patientName').textContent=context.patient.name||'반려동물';$('patientClinicName').textContent=context.connection.clinicName||'연결 병원';$('patientMeta').textContent=[speciesLabel(context.patient.species),context.patient.breed,sexLabel(context.patient.sex)].filter(Boolean).join(' · ');$('patientTimelineBody').hidden=true;$('patientTimelineLoading').hidden=false;$('patientTimelineLoading').innerHTML='<span class="home-spinner" aria-hidden="true"></span><b>병원 건강 기록을 불러오는 중입니다</b>';show('patientView');try{state.timeline=await api(`/home/patients/${encodeURIComponent(patientId)}/timeline?limit=300`,{method:'GET'});renderTimeline();$('patientTimelineLoading').hidden=true;$('patientTimelineBody').hidden=false;}catch(e){$('patientTimelineLoading').innerHTML=`<div class="home-timeline-empty"><b>건강 기록을 불러오지 못했습니다</b><p>${esc(e.message)}</p><button id="patientTimelineRetry" class="home-secondary" type="button">다시 시도</button></div>`;$('patientTimelineRetry')?.addEventListener('click',()=>openPatient(patientId));}}
  async function restore(){if(!state.token){show('loginView');return;}show('loadingView');try{const data=await api('/home/me',{method:'GET'});renderHome(data.home);show('dashboardView');}catch(e){if(e.status===401){state.token='';localStorage.removeItem(SESSION_KEY);show('loginView');}else showError(e.message);}}
  function showError(message){$('errorMessage').textContent=message||'병원에 새 초대 링크를 요청해주세요.';show('errorView');}
  async function logout(){const token=state.token;state.token='';localStorage.removeItem(SESSION_KEY);try{if(token){state.token=token;await api('/home/logout',{method:'POST'});}}catch{}finally{state.token='';state.home=null;state.timeline=null;show('loginView');}}
  function onlineStatus(){const offline=!navigator.onLine;$('offlineBar').hidden=!offline;}
  function bindInstall(){window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.installPrompt=e;$('installApp').hidden=false;});$('installApp').addEventListener('click',async()=>{if(!state.installPrompt)return;state.installPrompt.prompt();await state.installPrompt.userChoice;state.installPrompt=null;$('installApp').hidden=true;});window.addEventListener('appinstalled',()=>{$('installApp').hidden=true;state.installPrompt=null;});}
  async function init(){$('inviteForm').addEventListener('submit',acceptInvite);$('loginForm').addEventListener('submit',login);$('logoutButton').addEventListener('click',logout);$('homeHealthConsentSubmit').addEventListener('click',acceptHealthConsent);$('patientBack').addEventListener('click',()=>show('dashboardView'));$('patientTimelineRefresh').addEventListener('click',()=>state.active&&openPatient(state.active.patient.id));window.addEventListener('online',onlineStatus);window.addEventListener('offline',onlineStatus);onlineStatus();bindInstall();if('serviceWorker' in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});if(state.inviteToken)await loadInvite();else await restore();}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
