/* CARESTEP Clinic v9.4.2 · Korean veterinary breed dictionary */
(() => {
  'use strict';
  const breed=(name,en='',aliases=[])=>Object.freeze({name,en,aliases:Object.freeze(aliases)});

  const dog=[
    breed('믹스','Mixed Breed',['혼종','잡종','믹스견','mix','mixed']),
    breed('말티즈','Maltese',['마르티즈','몰티즈']),
    breed('푸들','Poodle',['스탠다드 푸들','미디엄 푸들']),
    breed('토이 푸들','Toy Poodle',['토이푸들']),
    breed('미니어처 푸들','Miniature Poodle',['미니푸들','미니어처푸들']),
    breed('포메라니안','Pomeranian',['포메']),
    breed('비숑 프리제','Bichon Frise',['비숑','비숑프리제']),
    breed('시츄','Shih Tzu',['시추']),
    breed('치와와','Chihuahua',['단모 치와와','장모 치와와']),
    breed('요크셔테리어','Yorkshire Terrier',['요키','요크셔 테리어','Yorkie']),
    breed('미니어처 슈나우저','Miniature Schnauzer',['미니슈나우저','미니어처슈나우저']),
    breed('닥스훈트','Dachshund',['닥스','미니어처 닥스훈트','장모 닥스훈트','단모 닥스훈트']),
    breed('웰시 코기 펨브로크','Pembroke Welsh Corgi',['웰시코기','코기','펨브로크']),
    breed('골든 리트리버','Golden Retriever',['골든','골든리트리버']),
    breed('래브라도 리트리버','Labrador Retriever',['라브라도','래브라도','랩','라브라도리트리버']),
    breed('진돗개','Korean Jindo Dog',['진도','진도견','Jindo']),
    breed('프렌치 불도그','French Bulldog',['프렌치불독','프불','프렌치 불독']),
    breed('시베리안 허스키','Siberian Husky',['허스키','시베리안허스키']),
    breed('사모예드','Samoyed',['사모']),
    breed('보더 콜리','Border Collie',['보더콜리','보콜']),
    breed('비글','Beagle',[]),
    breed('코커 스패니얼','Cocker Spaniel',['코카 스파니엘','코카스파니엘','코커스패니얼','코카']),
    breed('아메리칸 코커 스패니얼','American Cocker Spaniel',['아메리칸코커','아메코카']),
    breed('잉글리시 코커 스패니얼','English Cocker Spaniel',['잉글리시코커','잉글리쉬 코커']),
    breed('캐벌리어 킹 찰스 스패니얼','Cavalier King Charles Spaniel',['캐벌리어','카발리에','킹찰스']),
    breed('퍼그','Pug',[]),
    breed('페키니즈','Pekingese',['페키']),
    breed('파피용','Papillon',[]),
    breed('이탈리안 그레이하운드','Italian Greyhound',['이탈리안그레이하운드','이그']),
    breed('미니어처 핀셔','Miniature Pinscher',['미니핀','미니어처핀셔']),
    breed('잭 러셀 테리어','Jack Russell Terrier',['잭러셀','잭러셀테리어']),
    breed('스피츠','Spitz',['저먼 스피츠','재패니즈 스피츠','일본 스피츠']),
    breed('셰틀랜드 쉽독','Shetland Sheepdog',['셔틀랜드 쉽독','셸티','쉘티']),
    breed('시바 이누','Shiba Inu',['시바','시바견']),
    breed('아키타','Akita',['아키타견','아키타 이누']),
    breed('알래스칸 말라뮤트','Alaskan Malamute',['말라뮤트','알라스칸 말라뮤트']),
    breed('저먼 셰퍼드','German Shepherd Dog',['셰퍼드','세퍼드','저먼셰퍼드']),
    breed('도베르만 핀셔','Doberman Pinscher',['도베르만','도베르맨']),
    breed('로트와일러','Rottweiler',['롯트와일러','로트바일러']),
    breed('복서','Boxer',[]),
    breed('보스턴 테리어','Boston Terrier',['보스턴테리어']),
    breed('불도그','Bulldog',['잉글리시 불도그','불독','잉글리쉬 불독']),
    breed('아메리칸 불도그','American Bulldog',['아메리칸불독']),
    breed('아메리칸 불리','American Bully',['불리']),
    breed('불 테리어','Bull Terrier',['불테리어']),
    breed('스태퍼드셔 불 테리어','Staffordshire Bull Terrier',['스태피','스태퍼드셔불테리어']),
    breed('아메리칸 스태퍼드셔 테리어','American Staffordshire Terrier',['암스태프','아메리칸 스태퍼드셔']),
    breed('아메리칸 핏불 테리어','American Pit Bull Terrier',['핏불','핏불테리어']),
    breed('그레이트 데인','Great Dane',['그레이트데인']),
    breed('그레이트 피레니즈','Great Pyrenees',['피레니즈','그레이트피레니즈']),
    breed('버니즈 마운틴 독','Bernese Mountain Dog',['버니즈','버니즈마운틴독']),
    breed('뉴펀들랜드','Newfoundland',[]),
    breed('세인트 버나드','Saint Bernard',['세인트버나드']),
    breed('케인 코르소','Cane Corso',['카네코르소','케인코르소']),
    breed('불마스티프','Bullmastiff',['불 마스티프']),
    breed('티베탄 마스티프','Tibetan Mastiff',['티벳탄 마스티프','티베탄마스티프']),
    breed('그레이하운드','Greyhound',[]),
    breed('휘핏','Whippet',['위핏']),
    breed('보르조이','Borzoi',['러시안 울프하운드']),
    breed('바센지','Basenji',[]),
    breed('바셋 하운드','Basset Hound',['바셋하운드']),
    breed('블러드하운드','Bloodhound',['블러드 하운드']),
    breed('아프간 하운드','Afghan Hound',['아프간하운드']),
    breed('아이리시 울프하운드','Irish Wolfhound',['아이리시울프하운드']),
    breed('살루키','Saluki',[]),
    breed('포인터','Pointer',['잉글리시 포인터']),
    breed('와이마라너','Weimaraner',['바이마라너']),
    breed('비즐라','Vizsla',['비슬라']),
    breed('브리타니','Brittany',['브리타니 스패니얼']),
    breed('잉글리시 스프링어 스패니얼','English Springer Spaniel',['스프링거 스패니얼','잉글리시스프링어']),
    breed('달마시안','Dalmatian',['달마티안']),
    breed('오스트레일리안 셰퍼드','Australian Shepherd',['오시','호주 셰퍼드']),
    breed('오스트레일리안 캐틀 독','Australian Cattle Dog',['오스트레일리안캐틀독','블루 힐러']),
    breed('벨지안 말리노이즈','Belgian Malinois',['말리노이즈','벨지안 셰퍼드']),
    breed('올드 잉글리시 쉽독','Old English Sheepdog',['올드잉글리시쉽독']),
    breed('콜리','Collie',['러프 콜리','스무스 콜리']),
    breed('차우차우','Chow Chow',['차우 차우']),
    breed('샤페이','Shar Pei',['샤페이견']),
    breed('티베탄 스패니얼','Tibetan Spaniel',['티벳탄 스패니얼']),
    breed('라사압소','Lhasa Apso',['라사 압소']),
    breed('하바니즈','Havanese',[]),
    breed('꼬똥 드 툴레아','Coton de Tulear',['꼬똥','코튼 드 툴레아','꼬똥드툴레아']),
    breed('브뤼셀 그리펀','Brussels Griffon',['브뤼셀그리펀']),
    breed('차이니즈 크레스티드','Chinese Crested',['차이니즈크레스티드']),
    breed('재패니즈 친','Japanese Chin',['재패니즈친','칭']),
    breed('아펜핀셔','Affenpinscher',[]),
    breed('에어데일 테리어','Airedale Terrier',['에어데일테리어']),
    breed('케언 테리어','Cairn Terrier',['케언테리어']),
    breed('스코티시 테리어','Scottish Terrier',['스코티시테리어','스코티']),
    breed('웨스트 하이랜드 화이트 테리어','West Highland White Terrier',['웨스티','웨스트하이랜드화이트테리어']),
    breed('소프트 코티드 휘튼 테리어','Soft Coated Wheaten Terrier',['휘튼 테리어']),
    breed('실키 테리어','Australian Silky Terrier',['실키테리어']),
    breed('케리 블루 테리어','Kerry Blue Terrier',['케리블루테리어']),
    breed('스탠다드 슈나우저','Standard Schnauzer',['스탠다드슈나우저']),
    breed('자이언트 슈나우저','Giant Schnauzer',['자이언트슈나우저']),
    breed('스키퍼키','Schipperke',[]),
    breed('키스혼드','Keeshond',['케이스혼드']),
    breed('풍산개','Pungsan Dog',['풍산견']),
    breed('삽살개','Sapsali',['삽사리','삽살이']),
    breed('동경이','Donggyeongi',['경주개 동경이']),
    breed('제주개','Jeju Dog',['제주견']),
    breed('말티푸','Maltipoo',['말티즈 푸들 믹스']),
    breed('폼피츠','Pomspitz',['포메 스피츠 믹스']),
    breed('포메푸','Pomapoo',['포메라니안 푸들 믹스','폼푸']),
    breed('코카푸','Cockapoo',['코커 푸들 믹스']),
    breed('카바푸','Cavapoo',['캐벌리어 푸들 믹스']),
    breed('골든두들','Goldendoodle',['골든 리트리버 푸들 믹스']),
    breed('래브라두들','Labradoodle',['라브라두들','래브라도 푸들 믹스']),
    breed('기타 개 품종','Other Dog Breed',['기타','기타견','other'])
  ];

  const cat=[
    breed('코리안 쇼트헤어','Korean Shorthair',['코숏','코리안숏헤어','한국 고양이','한국고양이','Domestic Shorthair','DSH']),
    breed('믹스','Mixed Breed',['혼종','잡종','믹스묘','mix','mixed']),
    breed('러시안 블루','Russian Blue',['러시안블루','러블']),
    breed('페르시안','Persian',['페르시안 친칠라','친칠라']),
    breed('스코티시 폴드','Scottish Fold',['스코티쉬폴드','스코티시폴드','폴드']),
    breed('스코티시 스트레이트','Scottish Straight',['스코티쉬스트레이트','스트레이트']),
    breed('브리티시 쇼트헤어','British Shorthair',['브리티시숏헤어','브숏','British Short Hair']),
    breed('브리티시 롱헤어','British Longhair',['브리티시롱헤어','브롱']),
    breed('아메리칸 쇼트헤어','American Shorthair',['아메리칸숏헤어','아메숏']),
    breed('랙돌','Ragdoll',['렉돌']),
    breed('벵갈','Bengal',['뱅갈']),
    breed('샴','Siamese',['샤미즈','샤메즈','시암']),
    breed('터키시 앙고라','Turkish Angora',['터키쉬앙고라','터앙']),
    breed('아비시니안','Abyssinian',['아비']),
    breed('노르웨이 숲','Norwegian Forest Cat',['노르웨이숲','노르웨이안 포레스트','놀숲']),
    breed('메인쿤','Maine Coon',['메인 쿤']),
    breed('먼치킨','Munchkin',['먼치킨 롱레그','먼치킨 숏레그']),
    breed('스핑크스','Sphynx',['스핑크스 고양이']),
    breed('엑조틱 쇼트헤어','Exotic Shorthair',['엑조틱숏헤어','엑죠틱','엑조틱']),
    breed('소말리','Somali',[]),
    breed('시베리안','Siberian',['시베리안 포레스트']),
    breed('버만','Birman',['버먼']),
    breed('버미즈','Burmese',['버마고양이']),
    breed('봄베이','Bombay',[]),
    breed('차트룩스','Chartreux',['샤르트뢰']),
    breed('코랫','Korat',['코라트']),
    breed('이집션 마우','Egyptian Mau',['이집션마우']),
    breed('싱가푸라','Singapura',[]),
    breed('오시캣','Ocicat',['오시켓']),
    breed('오리엔탈 쇼트헤어','Oriental Shorthair',['오리엔탈숏헤어']),
    breed('오리엔탈 롱헤어','Oriental Longhair',['오리엔탈롱헤어']),
    breed('데본 렉스','Devon Rex',['데본렉스']),
    breed('코니시 렉스','Cornish Rex',['코니시렉스','코니쉬 렉스']),
    breed('셀커크 렉스','Selkirk Rex',['셀커크렉스']),
    breed('라팜','LaPerm',['라펌']),
    breed('아메리칸 컬','American Curl',['아메리칸컬']),
    breed('아메리칸 와이어헤어','American Wirehair',['아메리칸와이어헤어']),
    breed('발리니즈','Balinese',[]),
    breed('하바나 브라운','Havana Brown',['하바나브라운']),
    breed('히말라얀','Himalayan',['히말라얀 페르시안']),
    breed('재패니즈 밥테일','Japanese Bobtail',['재패니즈밥테일']),
    breed('맨섬','Manx',['맹크스','만스']),
    breed('킴릭','Cymric',['심릭']),
    breed('피터볼드','Peterbald',['피터발드']),
    breed('라가머핀','Ragamuffin',['라가머핀 고양이']),
    breed('사바나','Savannah',['사바나캣']),
    breed('토이거','Toyger',['토이저']),
    breed('통키니즈','Tonkinese',['톤키니즈']),
    breed('터키시 반','Turkish Van',['터키쉬 반']),
    breed('버밀라','Burmilla',[]),
    breed('카오 마니','Khao Manee',['카오마니']),
    breed('네벨룽','Nebelung',[]),
    breed('도메스틱 쇼트헤어','Domestic Shorthair',['도메스틱숏헤어','단모종','DSH']),
    breed('도메스틱 롱헤어','Domestic Longhair',['도메스틱롱헤어','장모종','DLH']),
    breed('기타 고양이 품종','Other Cat Breed',['기타','기타묘','other'])
  ];

  window.CARESTEP_BREEDS=Object.freeze({version:'KR-2026.09',dog:Object.freeze(dog),cat:Object.freeze(cat),other:Object.freeze([])});
})();
